### ISSUE TITLE
pypi discrepancies

### ISSUE THREAD

**Issue by mjpost** [aclements/biblib#2]
Is this code the latest version? pypi has 0.1.2 available, but the version string in the code here is 0.1.0. 

The pypi version also seems to require a non-existent module `magic` and a module `unidecode` which is not mentioned here in the source code...

**Comment by enkore** [comment]
https://pypi.org/project/biblib/

Is wholly unrelated to this package. It's a wrapper around pybtex.

**Comment by mjpost** [comment]
Got it, thanks.
